authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'authentication'
urlpatterns = [
    path('', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate_email, name='activate'),
    path('edit-register/', views.edit_register, name='edit_register'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('change-password/', views.change_password, name='change_password'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'),
         name='password_reset_complete'),
    path('set-password/', views.set_password, name='set_password'),
]

blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, FilterPostView, SearchPostView, post_detail, \
    post_list, category_detail, search, new_post, post_list_admin, \
    edit_post, delete_post, like_post

app_name = 'blog'
urlpatterns = [
    path('blog-list/', PostListView.as_view(), name='blog_list'),
    path('blog-detail/<slug:slug>/', PostDetailView.as_view(), name='blog_detail'),
    path('category-detail/<slug:slug>', category_detail, name='category_detail'),
    path('delete-post/<int:pk>/', delete_post, name='delete_post'),
    path('edit-post/<int:pk>/', edit_post, name='edit_post'),
    path('new-post/', new_post, name='new_post'),
    path('post-list/', post_list, name='post_list'),
    path('post-list-admin/', post_list_admin, name='post_list_admin'),
    path('post-detail/<slug:slug>/', post_detail, name='post_detail'),
    path('results/', search, name='search'),
    path('blog-list/filter', FilterPostView.as_view(), name='blog_list_filter'),
    path('blog-list/search', SearchPostView.as_view(), name='blog_list_search'),
    path('like-post/<int:pk>', like_post, name='like_post'),
]

galleries/urls.py
from django.urls import path

from galleries import views


app_name = "galleries"
urlpatterns = [
    path('', views.galleries_list, name="list"),
    path('add-gallery/', views.add_gallery, name='add_gallery'),
    path('<int:gallery_id>', views.gallery_details, name="details"),
    path('<int:gallery_id>/add/', views.add_photos, name='add_photos'),
    path('gallery-edit/<int:pk>', views.gallery_edit, name='gallery_edit'),
    path('gallery-delete/<int:pk>', views.gallery_delete, name='gallery_delete'),
    path('galleries-list-admin/', views.galleries_list_admin, name='galleries_list_admin'),
    path('galleries-list-view/', views.galleries_list_view, name='galleries_list_view'),
    path('galleries-list-view/<int:gallery_id>', views.photos_view, name='photos_view'),
    path('photo-delete/<int:pk>', views.photo_delete, name='photo_delete'),
    path('<int:pk>/photos-edit/', views.PhotosEditView.as_view(), name='photos_edit'),
    path('galleries-reminder/', views.galleries_reminder, name='galleries_reminder'),
]

main/urls.py
from django.urls import path
from . import views

# from .views import NewsletterUserListView, NewsletterUserDetailView
# from .api_views import CreateNewsletterUserApiView


app_name = 'main'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('about/', views.about, name='about'),
    path('user/create/', views.create_user_profile, name='create_user_profile'),
    path('user/profile/', views.user_profile, name='user_profile'),
    path('delete-user/', views.delete_user, name='delete_user'),
    path('contact/', views.contact, name='contact'),
    path('newsletter/sign-up/', views.newsletter_signup, name='newsletter_sign_up'),
    path('newsletter/unsubscribe/', views.newsletter_unsubscribe, name='newsletter_unsubscribe'),
    path('newsletter/users/', views.newsletter_users, name='newsletter_users'),
    path('newsletter/users-delete/<str:pk>/', views.newsletter_user_delete, name='newsletter_users_delete'),
    path('change-language/', views.change_language, name='change_language'),
    path('policy/', views.policy, name='policy'),
    path('accept-cookie-policy/', views.accept_cookie_policy, name='accept_cookie_policy'),
    path('cookie-banner/', views.cookie_banner, name='cookie_banner'),
    path('location/', views.api_location, name='api_location'),
    path('translate/', views.translate_app, name='translate_app'),
    path('accounts/social/signup/', views.signup_redirect, name='signup_redirect'),
    # path('newsletter/users/create/', CreateNewsletterUserApiView.as_view(), name='create_newsletter_user'),
    # path('newsletter/users/', NewsletterUserListView.as_view, name='newsletter_users'),
    # path('newsletter/users/<int:id>/', NewsletterUserDetailView.as_view, name='newsletter_user_detail'),
    path('api-avatars/', views.api_avatars, name='api_avatars'),
    path('show-avatars/', views.show_avatars, name='show_avatars'),
    path('toggle-mode/', views.toggle_mode, name='toggle_mode'),
]

plants_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

from .views import push_notification, send_push

urlpatterns = i18n_patterns(
    path('', include('main.urls')),
    path(_('admin/'), admin.site.urls),
    path('push_notification', push_notification, name='push_notification'),
    path('send_push', send_push),
    path('webpush/', include('webpush.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('authentication/', include('authentication.urls')),
    path('blog/', include('blog.urls')),
    path('control/', include('control_panel.urls')),
    path('galleries/', include('galleries.urls')),

    prefix_default_language=False,
)
# ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

if not settings.DEBUG:
    # handler = "app_name.views.function in views.py"
    handler403 = "plants_app.views.forbidden_403"
    handler404 = "plants_app.views.page_not_found_404"
    handler500 = "plants_app.views.error_500"

galleries/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from main.common import Timestamped, SlugMixin
from tinymce import models as tinymce_models

from plants_app import settings


class Status(models.IntegerChoices):
    HIDE = 1, "Hide"
    PUBLISHED = 2, "Published"


class Gallery(Timestamped, SlugMixin):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    # description = tinymce_models.HTMLField(null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.PositiveSmallIntegerField(default=Status.PUBLISHED, choices=Status.choices)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        verbose_name = "gallery"
        verbose_name_plural = "Galleries"

    def get_absolute_url(self):
        return reverse('galleries:details', kwargs={'gallery_id': self.pk})

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # if self.status == Status.HIDE:
        #     self.photos.update(status=Status.HIDE)
        super().save(*args, **kwargs)


def upload_to(instance, filename):
    return f"galleries/{instance.gallery.slug}/{filename}"


class Photo(Timestamped, SlugMixin):
    STATUS_CHOICES = (
        ('Once every 2-3 days', 'Once every 2-3 days'),
        ('Once a week', 'Once a week'),
        ('Once every 2 weeks', 'Once every 2 weeks'),
    )

    title = models.CharField(max_length=100)
    short_description = models.CharField(max_length=300, blank=True)
    how_often = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Once a week')
    image = models.ImageField(upload_to=upload_to)
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, related_name="photos")
    source = models.CharField(max_length=512, null=True, blank=True)
    status = models.PositiveSmallIntegerField(default=Status.PUBLISHED, choices=Status.choices)
    send_reminder = models.BooleanField(default=False, verbose_name='Send reminder to email')
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.title

    @property
    def is_published(self):
        return self.status == Status.PUBLISHED

galleries/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Gallery, Photo


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ["title", "description", "status"]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
        }


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ["title", "short_description", "image", "status", "source", "how_often", "send_reminder"]


# GalleryPhotosFormset = inlineformset_factory(Gallery, Photo, form=PhotoForm)
GalleryPhotosFormset = inlineformset_factory(Gallery, Photo, fields=("title",
                                                                     "short_description",
                                                                     "image",
                                                                     "status",
                                                                     "source",
                                                                     "how_often",
                                                                     "send_reminder"))

galleries/templates/galleries/add_gallery.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="col-md-6">
        <h4><b>Add your new plants gallery</b></h4>
        <br>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group" text-align="center">
                {{ form|crispy }}
            </div>
            {{ values|linebreaks }}
{#            <button type="submit" class="btn btn-primary">Submit</button>#}
        <div class="modal-footer">
            {% with url_name=request.resolver_match.url_name %}
                {% if url_name == 'add_gallery' %}
                        <button class="btn btn-primary" type="submit">Save</button>
                        <a class="btn btn-dark" href="{% url 'main:home_page' %}" role="button">Back</a>
                {% elif url_name == 'gallery_edit' %}
                        <button class="btn btn-warning" type="submit">Edit</button>
                        <a class="btn btn-dark" href="{% url 'galleries:list' %}" role="button">Back</a>
                {% else %}
                        <button class="btn btn-danger" type="submit">Delete</button>
                        <a class="btn btn-dark" href="{% url 'galleries:list' %}" role="button">Back</a>
                {% endif %}
            {% endwith %}
        </div>
        </form>
    </div>
    {{ values|linebreaks }}
{% endblock %}

galleries/templates/galleries/add_photos.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}


{% block title %}Add photos{% endblock %}
{% block content %}
    {% if user.id != gallery.author.id %}
        <div class="card-title text-center">
            <b>Not your gallery: you must be logged in as a proper user:
                <a href="{% url 'authentication:login_user' %}" class="btn btn-primary">Sign-in</a>
            </b>
        </div>
    {% else %}
{#    {% if messages %}#}
{#        {% for message in messages %}#}
{#            <div class="alert {{ message.tags }} alert-dismissible" role="alert">#}
{#                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>#}
{#                {{ message|striptags|safe|linebreaksbr }}#}
{#            </div>#}
{#        {% endfor %}#}
{#    {% endif %}#}
    <div class="row">
        {% for gallery in page_obj %}
            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    {% thumbnail gallery.photos.first.image "300x300" crop="center" as im %}
                        <img class="card-img-top" src="{{ im.url }}" alt="">
                    {% endthumbnail %}
                    <div class="card-body">
                        <h4 class="card-title text-center">{{ gallery.title }}</h4>
                    </div>
                    <div class="card-footer text-center">
                        <a href="{% url "galleries:details" gallery.id %}" class="btn btn-primary">Show</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% endif %}
        {% if gallery_form %}
            <div class="row">
                <div class="col-6 offset-md-3">
                    <form id="gallery_form" method="post" action=".">
                        {% csrf_token %}
                        {{ gallery_form|crispy }}
                        <input type="submit" name="submit" value="Submit" class="btn btn-primary"/>
                    </form>
                </div>
            </div>
        {% endif %}
        {% if formset %}
            <div class="row">
                <h3><b>Add photos to your gallery: </b>{{ gallery.title }}</h3><hr>
                <div><br>
                    {% for photo in gallery.photos.all %}
                        {% thumbnail gallery_image.image "x80" as im %}
                            <img src="{{ im.url }}" alt=""/>
                        {% endthumbnail %}
                    {% endfor %}
                </div>
                <div class="col-6 offset-md-3">
                    <form id="form-container" method="post" action="." enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ formset.management_form}}
                        {% for form in formset %}
                            {{ values|linebreaks }}
                            <div class="photo-form">
                                {{ form|crispy }}
                                <br>
                            </div>
                        {% endfor %}
                        <br>
                        <button id="add-form" type="button" class="btn btn-info">Add another one</button>
                        <hr>
                        <input type="submit" name="submit" value="Save" class="btn btn-primary"/>
                    </form>
                    <div style="text-align: right; font-size: medium">
                        <a href="{% url 'galleries:list' %}"><button class="btn btn-secondary">Back to list</button></a>
                    </div>
                </div>
            </div>
        {% endif %}
{% endblock %}
{% block additional_scripts %}
    {{ gallery_form.media }}
    <script>
        let form = document.querySelectorAll(".photo-form")
        let container = document.querySelector("#form-container")
        let addButton = document.querySelector("#add-form")
        let totalForms = document.querySelector("#id_form-TOTAL_FORMS")
        let formNum = form.length - 1
        addButton.addEventListener("click", addForm)
        function addForm(e) {
            e.preventDefault()
            let newForm = form[0].cloneNode(true)
            let formRegex = RegExp(`form-(\\d){1}-`, "g")
            formNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
            container.insertBefore(newForm, addButton)
            totalForms.setAttribute("value", `${formNum + 1}`)
        }
    </script>
    <br><br>
{% endblock %}

galleries/templates/galleries/galleries_list_view.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}Galleries{% endblock %}
{% block content %}
    <div class="row">
        {% for gallery in page_obj %}
            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    {% if gallery.photos.first.status == 2 %}
                        {% thumbnail gallery.photos.first.image "300x300" crop="center" as im %}
                            <img class="card-img-top" src="{{ im.url }}" alt="">
                        {% endthumbnail %}
                    {% else %}
                        <img class="card-img-top" width="300" height="300" src="{% static "main/img/gallery-cover-photo.jpg" %}" alt="cover-photo">
                    {% endif %}
                    <div class="card-body">
                        <h4 class="card-title text-center">{{ gallery.title }}</h4>
                    </div>
                    <div class="galleries">
                        {{ gallery.description|safe }}
{#                        {{ gallery.description|slice:":50"|safe }}#}
                    </div>
                    <div class="card-footer text-center">
                        <a href="{% url "galleries:photos_view" gallery_id=gallery.id %}" class="btn btn-primary">Show</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div style="text-align: right; font-size: medium">
        <a href="{% url 'galleries:list' %}"><button class="btn btn-secondary">Back to list</button></a>
    </div>
    {% include 'pagination.html' %}
    {% if gallery_form %}
        <div class="row">
            <div class="col-6 offset-md-3">
                <form id="gallery_form" method="post" action=".">
                    {% csrf_token %}
                    {{ gallery_form|crispy }}
                    <input type="submit" name="submit" value="Submit" class="btn btn-primary"/>
                </form>
            </div>
        </div>
    {% endif %}
{% endblock %}

galleries/templates/galleries/gallery_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if user.id != gallery.author.id %}
        <div class="card-title text-center">
            <b>Not your gallery: you must be logged in as a proper user:
                <a href="{% url 'authentication:login_user' %}" class="btn btn-primary">Sign-in</a>
            </b>
        </div>
    {% else %}
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card card-body">
                <p style="text-align: center">Are you sure you want to delete: "{{ gallery }}"?</p>
                <form action="{% url 'galleries:gallery_delete' gallery.id  %}" method="POST">
                    {% csrf_token %}
                    <p style="text-align: center">
                        <input class="btn btn-primary" type="submit" value="Confirm">
                        <a class="btn btn-danger" href="{% url 'galleries:list' %}">Cancel</a>
                    </p>
                </form>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

galleries/templates/galleries/gallery_details.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
    {% if user.id != gallery.author.id %}
        <div class="card-title text-center">
            <b>Not your gallery: you must be logged in as a proper user:
                <a href="{% url 'authentication:login_user' %}" class="btn btn-primary">Sign-in</a>
            </b>
        </div>
    {% else %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                {{ message|striptags|safe|linebreaksbr }}
            </div>
        {% endfor %}
    {% endif %}
        <div style="text-align: right; font-size: medium">
            <a href="{% url 'galleries:list' %}"><button class="btn btn-secondary">Back to list</button></a>
        </div><br>
        <div class="card card-body special-cards">
            <h2><b>{{ gallery.title }}</b></h2>
        <div style="text-align: right">
            <td><a href="{% url 'galleries:photos_edit' pk=gallery.id %}">
                <button class="btn btn-primary">Edit photos</button></a>
            </td><hr>
        </div>
{#            {% if user.id == gallery.author.id %}#}
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="table-responsive table-hover">
                        <table class="table">
                            <thead class="thead-dark">
                            <tr style="text-align: center">
                                <th scope="col">Title</th>
                                <th scope="col">Slug</th>
                                <th scope="col">Short description</th>
                                <th scope="col">Status</th>
                                <th scope="col">How often</th>
                                <th scope="col">Send reminder</th>
                                <th scope="col">Created</th>
                                <th scope="col">Updated</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for gallery_image in page_obj %}
                                {% if gallery_image.is_published %}
                                    <tr style="text-align: center">
                                        <td>{{ gallery_image.title }}</td>
                                        <td>{{ gallery_image.slug }}</td>
                                        <td>{{ gallery_image.short_description }}</td>
                                        <td>{{ gallery_image.get_status_display }}</td>
                                        <td>{{ gallery_image.how_often }}</td>
                                        <td>{{ gallery_image.send_reminder }}</td>
                                        <td>{{ gallery_image.created }}</td>
                                        <td>{{ gallery_image.updated }}</td>
                                        <td><a href="{% url 'galleries:photo_delete' pk=gallery_image.pk %}"><button class="btn btn-danger">Delete</button></a></td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
{#            {% endif %}#}
            <br/>
        </div>
        {{ values|linebreaks }}
    {% endif %}
    {% include 'pagination.html' %}

{% endblock %}

galleries/templates/galleries/list_galleries.html
{% extends 'base.html' %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                {{ message|striptags|safe|linebreaksbr }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="row">
            <div style="text-align: inherit; font-size: medium">
                <h5 class="page-header"><b>All galleries: </b></h5><br>
            </div>
        </div>
    </div>
    <div class="card card-body special-cards">
{#    <div class="table-responsive table-hover">#}
        <table class="table">
            <thead class="thead-dark">
                <tr style="text-align: center">
                    <th scope="col">Title</th>
{#                    <th scope="col">Slug</th>#}
                    <th scope="col">Number of photos</th>
                    <th scope="col">Created</th>
                    <th scope="col">Updated</th>
                    <th scope="col">Status</th>
                    <th scope="col">View galleries</th>
                    <th scope="col">Add Photos</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
            {% for item in gallery %}
                <tr style="font-weight: normal; text-align: center">
                    <td>{{ item.title }}</td>
{#                    <td>{{ item.slug }}</td>#}
                    <td>{{ item.photos.count }}</td>
                    <td>{{ item.created }}</td>
                    <td>{{ item.updated }}</td>
                    <td>{{ item.get_status_display }}</td>
                    {% if item.status == 1 %}
                        <td><button class="btn btn-info" disabled>Gallery is hidden</button></td>
                    {% else %}
                        <td><a href="{% url 'galleries:details' gallery_id=item.pk %}"><button class="btn btn-info">Gallery details</button></a></td>
                    {% endif %}
                    <td><a href="{% url 'galleries:add_photos' gallery_id=item.pk %}"><button class="btn btn-primary">Add photos</button></a></td>
                    <td><a href="{% url 'galleries:gallery_edit' pk=item.pk %}"><button class="btn btn-warning">Edit</button></a></td>
                    <td><a href="{% url 'galleries:gallery_delete' pk=item.pk %}"><button class="btn btn-danger">Delete</button></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <br>
    <footer>
        <div style="text-align: right; font-size: medium">
            <button type="button" class="btn button-pills">
                <a href="{% url 'galleries:add_gallery' %}" class="nav-link">New gallery</a>
            </button>
            <button type="button" class="btn button-pills">
                <a href="{% url 'main:home_page' %}" class="nav-link">Back</a>
            </button>
        </div>
    </footer>
    <br><br>
    {% include 'pagination.html' %}
{% endblock %}

galleries/templates/galleries/photo_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if user.id != photo.gallery.author.id %}
        <div class="card-title text-center">
            <b>Not your gallery: you must be logged in as a proper user:
                <a href="{% url 'authentication:login_user' %}" class="btn btn-primary">Sign-in</a>
            </b>
        </div>
    {% else %}
        <div class="row justify-content-center">
            <div class="col-md-5">
                <div class="card card-body">
                    <p style="text-align: center">Are you sure you want to delete: "{{ photo }}"?</p>
                    <form action="{% url 'galleries:photo_delete' photo.id  %}" method="POST">
                        {% csrf_token %}
                        <p style="text-align: center">
                            <input class="btn btn-primary" type="submit" value="Confirm">
                            <a class="btn btn-danger" href="{% url 'galleries:details' gallery_id=photo.gallery.id %}">Cancel</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

galleries/templates/galleries/photos_view.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Gallery photos{% endblock %}
{% block content %}
    {% if user.id != gallery.author.id %}
        <div class="card-title text-center">
            <b>Not your gallery: you must be logged in as a proper user:
                <a href="{% url 'authentication:login_user' %}" class="btn btn-primary">Sign-in</a>
            </b>
        </div>
    {% else %}
    <div style="text-align: right; font-size: medium">
        <a href="{% url 'galleries:galleries_list_view' %}"><button class="btn btn-secondary">Back to list</button></a>
    </div><br>

    <!-- Gallery Images -->
        <div class="card card-body">
            <div class="container">
                {% if user.id == gallery.author.id %}
                    <h3 class="fw-light text-center text-lg-start mt-4 mb-0">{{ gallery.title }}</h3>
                    <hr class="mt-2 mb-5">
                    <div class="row text-center text-lg-start">
                        {% for gallery_image in gallery.photos.all %}
                            {% if gallery_image.is_published %}
                                <div class="col-lg-3 col-md-4 col-6">
                                {% thumbnail gallery_image.image "x300" as im %}
                                    <a href="{{ gallery_image.image.url }}" class="d-block mb-4 h-100">
                                        <img class="img-fluid img-thumbnail" src="{{ im.url }}" alt="image">
                                    </a>
                                {% endthumbnail %}
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
        <br/><br/>
    {% endif %}
{% endblock %}