authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'authentication'
urlpatterns = [
    path('', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate_email, name='activate'),
    path('edit-register/', views.edit_register, name='edit_register'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('change-password/', views.change_password, name='change_password'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'),
         name='password_reset_complete'),
    path('set-password/', views.set_password, name='set_password'),
]

blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, FilterPostView, SearchPostView, post_detail, \
    post_list, category_detail, search, new_post, post_list_admin, \
    edit_post, delete_post, like_post

app_name = 'blog'
urlpatterns = [
    path('blog-list/', PostListView.as_view(), name='blog_list'),
    path('blog-detail/<slug:slug>/', PostDetailView.as_view(), name='blog_detail'),
    path('category-detail/<slug:slug>', category_detail, name='category_detail'),
    path('delete-post/<int:pk>/', delete_post, name='delete_post'),
    path('edit-post/<int:pk>/', edit_post, name='edit_post'),
    path('new-post/', new_post, name='new_post'),
    path('post-list/', post_list, name='post_list'),
    path('post-list-admin/', post_list_admin, name='post_list_admin'),
    path('post-detail/<slug:slug>/', post_detail, name='post_detail'),
    path('results/', search, name='search'),
    path('blog-list/filter', FilterPostView.as_view(), name='blog_list_filter'),
    path('blog-list/search', SearchPostView.as_view(), name='blog_list_search'),
    path('like-post/<int:pk>', like_post, name='like_post'),
]

main/urls.py
from django.urls import path
from . import views

# from .views import NewsletterUserListView, NewsletterUserDetailView
# from .api_views import CreateNewsletterUserApiView


app_name = 'main'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('about/', views.about, name='about'),
    path('user/create/', views.create_user_profile, name='create_user_profile'),
    path('user/profile/', views.user_profile, name='user_profile'),
    path('delete-user/', views.delete_user, name='delete_user'),
    path('contact/', views.contact, name='contact'),
    path('newsletter/sign-up/', views.newsletter_signup, name='newsletter_sign_up'),
    path('newsletter/unsubscribe/', views.newsletter_unsubscribe, name='newsletter_unsubscribe'),
    path('newsletter/users/', views.newsletter_users, name='newsletter_users'),
    path('newsletter/users-delete/<str:pk>/', views.newsletter_user_delete, name='newsletter_users_delete'),
    path('change-language/', views.change_language, name='change_language'),
    path('policy/', views.policy, name='policy'),
    path('accept-cookie-policy/', views.accept_cookie_policy, name='accept_cookie_policy'),
    path('cookie-banner/', views.cookie_banner, name='cookie_banner'),
    path('location/', views.api_location, name='api_location'),
    path('translate/', views.translate_app, name='translate_app'),
    path('accounts/social/signup/', views.signup_redirect, name='signup_redirect'),
    # path('newsletter/users/create/', CreateNewsletterUserApiView.as_view(), name='create_newsletter_user'),
    # path('newsletter/users/', NewsletterUserListView.as_view, name='newsletter_users'),
    # path('newsletter/users/<int:id>/', NewsletterUserDetailView.as_view, name='newsletter_user_detail'),
    path('api-avatars/', views.api_avatars, name='api_avatars'),
    path('show-avatars/', views.show_avatars, name='show_avatars'),
    path('toggle-mode/', views.toggle_mode, name='toggle_mode'),
]

plants_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

from .views import push_notification, send_push

urlpatterns = i18n_patterns(
    path('', include('main.urls')),
    path(_('admin/'), admin.site.urls),
    path('push_notification', push_notification, name='push_notification'),
    path('send_push', send_push),
    path('webpush/', include('webpush.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('authentication/', include('authentication.urls')),
    path('blog/', include('blog.urls')),
    path('control/', include('control_panel.urls')),
    path('galleries/', include('galleries.urls')),

    prefix_default_language=False,
)
# ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

if not settings.DEBUG:
    # handler = "app_name.views.function in views.py"
    handler403 = "plants_app.views.forbidden_403"
    handler404 = "plants_app.views.page_not_found_404"
    handler500 = "plants_app.views.error_500"

blog/forms.py
from django import forms

from .models import Post, Images


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        fields = ['title', 'description', 'place', 'category', 'status', 'image', 'file']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'place': forms.TextInput(attrs={'class': 'forms-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'file': forms.FileInput(attrs={'class': 'form-control-file', 'multiple': False})
        }


class ImagesForm(forms.ModelForm):
    class Meta:
        model = Images
        fields = ['images']
        widgets = {
            'images': forms.ClearableFileInput(attrs={'multiple': True}),  # to add multiple images
        }

blog/views.py
from django import template
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMultiAlternatives, BadHeaderError
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import get_template
from django.views.generic.list import ListView
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.generics import ListAPIView
from rest_framework.pagination import PageNumberPagination

from plants_app.config import pagination
from .models import Post, Category, Images
from .forms import PostForm, ImagesForm
from plants_app import settings
from main.models import NewsletterUser
from .serializers import PostSerializer


class PostListView(ListView):
    model = Post
    paginate_by = 5
    context_object_name = 'posts'
    template_name = 'blog/post_list.html'

    def get_queryset(self):
        if self.request.method == 'GET' and 'orderby' in self.request.GET:
            order_by = self.request.GET.get('orderby', 'id')
            if order_by is not None and order_by != '':
                posts = Post.objects.all().order_by(order_by)
        else:
            posts = Post.objects.all().order_by('-created')

        return posts

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['orderby'] = self.request.GET.get('orderby', 'id')
        # context['all_table_fields'] = Post._meta.get_fields()
        return context


class PostDetailView(ListView):
    model = Post
    template_name = 'blog/post_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(PostDetailView, self).get_context_data(*args, **kwargs)
        stuff = get_object_or_404(Post, id=self.kwargs['pk'])
        num_likes = stuff.num_likes()
        context["num_likes"] = num_likes

        return context


# API
class FilterPostView(ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    filter_backends = (OrderingFilter, DjangoFilterBackend)
    ordering_fields = ('created', 'updated', 'place', 'author', 'category')
    ordering = ('created',)  # Default posts ordering.


class SearchPostView(ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    filter_backends = (SearchFilter, DjangoFilterBackend)
    search_fields = ('title', 'description')
    pagination_class = PageNumberPagination


def post_list(request):
    object_list = Post.objects.filter(status='Published')
    pages = pagination(request, object_list, 15)

    template = 'blog/post_list.html'
    context = {
        'post_list': object_list,
        'page_obj': pages
    }

    return render(request, template, context)


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    files = Images.objects.filter(images=Images.images)

    template = 'blog/post_detail.html'
    context = {
        'post': post,
        'files': files
    }

    return render(request, template, context)


def category_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    post = Post.objects.filter(category=category, status='Published')

    template = 'blog/category_detail.html'
    context = {
        'category': category,
        'post': post
    }
    return render(request, template, context)


def search(request):
    query = request.GET.get('q')
    if query:
        results = Post.objects.filter(Q(title__icontains=query) | Q(description__icontains=query))
    else:
        results = Post.objects.filter(status='Published')

    pages = pagination(request, results, num=3)

    template = 'blog/post_list.html'
    context = {
        'page_obj': pages,
        'query': query,
        'object_list': pages,
    }

    return render(request, template, context)


@login_required(login_url='/authentication/login')
def new_post(request):
    form = PostForm(request.POST, request.FILES)
    img_form = ImagesForm(request.POST, request.FILES)
    image = request.FILES.getlist('images')  # field name in model
    image_list = []

    if form.is_valid() and img_form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()
        # We should be updating the instance not the form, if we write:
        # img_form.save() and form.save() this will give us an error.
        for img in image:
            image_instance = Images.objects.create(images=img, post=instance)
            image_instance.save()
            image_list.append(image_instance)

        messages.success(request, 'New post has been successfully added!')
        if form.data['status'] == 'Published':
            send_email_if_new_post(form)

        return redirect('main:home_page')

    else:
        form = PostForm()
        img_form = ImagesForm()

    return render(request, 'blog/new_post.html', {'form': form, 'img_form': img_form, 'image_list': image_list})


@login_required
def edit_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    user = request.user
    form = PostForm(instance=post)

    if request.method == 'POST' and user.id == post.author.id:
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'The blog post has been updated!')
            return redirect('blog:blog_list')

    elif request.method == 'POST' and user.id != post.author.id:
        messages.warning(request, 'Not your blog post, you must be log in as a proper user to edit/delete.')

    return render(request, 'blog/new_post.html', {'form': form, 'post': post})


@login_required
def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    user = request.user
    form = PostForm(instance=post)
    if request.method == 'POST' and user.id == post.author.id:
        post.delete()
        form = PostForm()
        messages.success(request, 'You have successfully delete the post.')

    elif request.method == 'POST' and user.id != post.author.id:
        messages.warning(request, 'Not your blog post, your must be login as a proper user to edit/delete')

    else:
        form = PostForm(instance=post)

    template = 'blog/new_post.html'
    context = {
        'form': form,
        'post': post
    }

    return render(request, template, context)


@staff_member_required
def post_list_admin(request):
    post = Post.objects.all()
    pages = pagination(request, post, 10)

    template = 'blog/post_list_admin.html'
    context = {
        'post_list_admin': pages,
        'page_obj': pages
    }

    return render(request, template, context)


def send_email_if_new_post(form):
    subscribers = NewsletterUser.objects.all()
    title = f"New post has been added to blog: {form.data['title']} "
    body = {
        'description': form.data['description'],
    }
    plaintext = template.loader.get_template('blog/new_post_form.txt')
    htmltemp = template.loader.get_template('blog/new_post_form.html')
    from_email = settings.EMAIL_HOST_USER
    text_content = plaintext.render(body)
    html_content = htmltemp.render(body)

    for sub in subscribers:
        try:
            msg = EmailMultiAlternatives(title, text_content, from_email, [sub.email],
                                         headers={'Reply-To': "email@gmail.com"})
            msg.attach_alternative(html_content, 'text/html')
            msg.send()
        except BadHeaderError:
            return HttpResponse('Invalid header found.')

    # for sub in subscribers:
    #     send_mail(subject=f"New post has been added to blog: {title}",
    #               message=f"{body}", from_email=settings.EMAIL_HOST_USER,
    #               recipient_list=[sub.email], fail_silently=True)
    #


def like_post(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)

    return redirect('blog:post_detail', slug=post.slug)

blog/templates/blog/category_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="card card-body">
        <h2><i><b>Category: </b>{{ category.title }}</i></h2><hr><br>
        <p><i><b>Description: </b>{{ category.description }}</i></p>
{#    {{ category.get_absolute_url }}#}
    </div><br>
    <div class="card card-body">
        {% for item in post %}
            <div class="card card-body">
                <h4><b>Post: '{{ item.title }}'</b></h4>
                {{ item.description|truncatechars:50 }}
            </div>
            {{ value|linebreaks }}
        {% endfor %}
    </div><br>
    <div style="text-align: right; font-size: medium">
        <a href="{% url 'blog:blog_list' %}"><button class="btn btn-secondary">Back to list</button></a>
    </div>
{% endblock %}

blog/templates/blog/new_post.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% with url_name=request.resolver_match.url_name %}
        {% if url_name == 'new_post' %}
            <h4><b>Add a new post</b></h4>
        {% elif url_name == 'edit_post'%}
            <h4><b>Edit post: </b>{{ post.title }}</h4>
        {% else %}
            <h4>Delete post: {{ post.title }}</h4>
        {% endif %}
    {% endwith %}<br>
    <div class="col-md-6">
    <form action="" method="post"  enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form|crispy }}
            {{ img_form|crispy }}
{#            {{ form.media }}  # We can add images to text, bold, italics text etc. #}
        </div>
        {{ values|linebreaks }}
        <div class="modal-footer">
        {% with url_name=request.resolver_match.url_name %}
            {% if url_name == 'new_post' %}
                <button class="btn btn-primary" type="submit">Save</button>
                <a class="btn btn-dark" href="{% url 'main:home_page' %}" role="button">Back</a>
            {% elif url_name == 'edit_post' %}
                <button class="btn btn-warning" type="submit">Edit</button>
                <a class="btn btn-dark" href="{% url 'blog:post_detail' slug=post.slug %}" role="button">Back</a>
            {% else %}
                <button class="btn btn-danger" type="submit">Delete</button>
                <a class="btn btn-dark" href="{% url 'blog:blog_list' %}" role="button">Back</a>
            {% endif %}
        {% endwith %}
        </div>
    </form>
    </div>
    {{ values|linebreaks }}
{% endblock %}

blog/templates/blog/new_post_form.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="">
  <head>
    <title>HTML blog post template</title>
    <meta name="viewport" content="width = 375, initial-scale = -1">
  </head>
  <body style="background-color: lightgoldenrodyellow; font-size: 16px;">
    <div style="text-align: center;">
      <table align="center" border="0" cellpadding="0" cellspacing="0" style="height:100%; width:600px;">
          <!-- BEGIN EMAIL -->
          <tr>
            <td align="center" bgcolor="#fffaf0" style="padding:30px">
               <p style="text-align:left">
                   <b><i>See new post about: </i></b>
                   <br>
               </p>
                <p style="text-align:left">
                    <i>'{{ description|safe }}'</i>
                </p>
                <br><br>

                <p style="text-align:left">For more visit our website:
                    <a href="{{ 'https' }}://{{ 'plants-mw.herokuapp.com/' }}"><b>watering-plants-app.com</b></a>
                </p>
                <p style="text-align:left">
                    Kind regards,<br>The Watering Plants Application Team
                </p>
            </td>
          </tr>
      </table>
    </div>
  </body>
</html>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block content %}
    <div style="text-align: right; font-size: medium">
        <a href="{% url 'blog:blog_list' %}"><button class="btn btn-secondary">Back to list</button></a>
    </div><br>
    <div class="card card-body">
        <h3><b>{{ post.title }}</b></h3>
        {% if user.is_authenticated %}
            {% if user.id == post.author.id %}
                <div class="button-box col-lg-12">  <! -- buttons next to each other ––>
                    <a href="{% url 'blog:edit_post' pk=post.pk %}"><button class="btn btn-primary">Edit</button></a>
                    <a href="{% url 'blog:delete_post' pk=post.pk %}"><button class="btn btn-danger" >Delete</button></a>
                </div>
            {% endif %}
        {% endif %}
        {{ values|linebreaks }}
        <div class="card card-body">
            <small><b>Published: </b>{{ post.created }}</small>
            {% if post.updated %}
            {{ value|linebreaks }}
                <small><b>Updated: </b>{{ post.updated }}</small>
        </div>
        <div class="card card-footer">
{#            <b>Location: </b>{{ post.place }}#}
{#            {{ value|linebreaks }}#}
            {% endif %}
                {{ post.description|safe }}
        </div>
        {{ value|linebreaks }}
        {% if post.image %}
            {% thumbnail post.image "x320" as im %}
                <p style="text-align:center"><a href="{{ post.image.url }}">
                    <img class="img-fluid img-thumbnail" src="{{ im.url }}" alt="" title="image for post: {{ post.pk }}"/></a>
                </p>
            {% endthumbnail %}
        {% endif %}
        {% if post.file %}
            <div>
                <a href="{{ post.file.url }}">
                    <button class="btn btn-primary"><i class="fa fa-download"></i> Download attached file </button>
                </a>
            </div>
        {% endif %}

        <!-- Multiple images -->
        {% if post.images.exists %}
            <hr class="mt-2 mb-5">
            <div class="row text-center text-lg-start">
                {% for image in post.images.all %}
                    <div class="col-lg-3 col-md-4 col-6">
                        {% thumbnail image.images "x320" as img %}
                            <a href="{{ image.images.url }}" class="d-block mb-4 h-100">
                                <img class="img-fluid img-thumbnail" src="{{ img.url }}" alt="image">
                            </a>
                        {% endthumbnail %}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <br/><br/>
        <hr>
        <br/>
        <form action="{% url 'blog:like_post' pk=post.pk %}" method="POST">
            {% csrf_token %}
            {% if user.is_authenticated %}
                {% if request.user in post.likes.all %}
                    <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-danger">Unlike</button>
                {% else %}
                    <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-primary">Like</button>
                {% endif %}
            {% else %}
                <small>You must be <a href="{% url 'authentication:login_user' %}">logged in </a>to like</small>
            {% endif %}
            - {{ post.num_likes }} Likes
        </form>
    </div>
    {{ values|linebreaks }}
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}

{#{% block styles %}#}
{#    <link href="{% static "/main/css/style.css" %}" rel="stylesheet">#}
{#{% endblock %}#}

{% block content %}
    <div style="display: flex; justify-content: flex-end">Current login user: &nbsp;<b>'{{ user.username|default:'Guest'}}'</b></div>
    <div class="container">
        <div class="header-bottom-set dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Order by:
            </button>
            <ul class="dropdown-menu dropdown-menu-left">
                <li><a class="dropdown-item" href="{% url 'blog:blog_list' %}?orderby=-created">newest</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:blog_list' %}?orderby=-updated">updated</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:blog_list' %}?orderby=author">author</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:blog_list' %}?orderby=place">place</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:blog_list' %}?orderby=category">category</a></li>
            </ul>
        </div>
        <div style="text-align: center;">
            <form method="GET" action="{% url 'blog:search' %}">
                <input name="q" value="{{ request.GET.q }}" placeholder="search..">
                <button class="btn btn-primary" type="submit" >Search&nbsp;
                    <i class="fa-solid fa-magnifying-glass fa-beat-fade"></i>
                </button>
                {% csrf_token %}
{#                <img src="{% static "img/search.png" %}" alt="logo" width="2.1%">#}
            </form>
        </div>
        <br>
        {% for obj in object_list %}
            {{ values|linebreaks }}
            <div class="card card-body">
             <h3 class="card-title"><a href="{% url 'blog:post_detail' slug=obj.slug %}">{{ obj.title|capfirst }}</a></h3>
                {{ values|linebreaks }}
                <p class="card-text text-muted h6"><b>Published: </b>{{ obj.created }} by <b>{{ obj.author }}
                    {% if obj.author.first_name %} ({{ obj.author.first_name }}) {% endif %}</b></p>
                <p class="card-text text-muted h6"><b>Updated: </b>{{ obj.updated }}</p>
                <p class="card-text text-muted h6"><b>Location: </b>{{ obj.place }}</p>
                <div class="card-footer">
                    <div class="row justify-content-md-center">
                        <div class="col-md-7">
                            <div class="ratio ratio-4x3">
                                <img class="img-fluid img-thumbnail" src="{{ obj.image.url }}" alt="{{ obj.title }}">
                                <section oncontextmenu="return false"></section>
                                <!-- not allowed to copy/download images from 'blog list' page -->
                            </div>
                        </div>
                    </div>
                    <p class="card-text"><small>{{ obj.description|slice:":150"|safe }}</small></p>
                    <a href="{% url 'blog:post_detail' obj.slug %}" class="btn btn-primary">Read more &rarr;</a>
                </div>
                {{ values|linebreaks }}
                <div class="card-footer">
        {#            <p><b>Author: </b>{{ obj.author }}</p>#}
                    <p><b><small>Category: </small></b><a href="{% url 'blog:category_detail' slug=obj.category.slug %}">{{ obj.category }}</a></p>
                </div>
            </div>
        {% endfor %}
        {% include 'pagination.html' %}
    </div>
{% endblock %}

blog/templates/blog/post_list_admin.html
{% extends 'base.html' %}

{% block content %}
    <div class="card card-body special-cards">
        <table class="table">
            <thead class="thead-dark">
                <tr style="text-align: center">
                    <th scope="col">PK</th>
                    <th scope="col">Post Title</th>
                    <th scope="col">Slug</th>
                    <th scope="col">Author</th>
                    <th scope="col">Category</th>
                    <th scope="col">Likes</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
            {% for item in page_obj %}
                <tr style="text-align: center">
                    <td>{{ item.pk }}</td>
                    <td>{{ item.title }}</td>
                    <td>{{ item.slug }}</td>
                    <td>{{ item.author }}</td>
                    <td>{{ item.category }}</td>
                    <td>{{ item.likes.count }}</td>
                    <td><a href="{% url 'blog:delete_post' pk=item.pk %}"><button class="btn btn-danger">Delete</button></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% include 'pagination.html' %}
    <footer>
    <br>
        <div style="text-align: right; font-size: medium">
            <button type="button" class="btn btn-light">
                <a href="{% url 'main:home_page' %}" class="nav-link">Back</a>
            </button>
        </div>
    </footer>
{% endblock %}