authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'authentication'
urlpatterns = [
    path('', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate_email, name='activate'),
    path('edit-register/', views.edit_register, name='edit_register'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('change-password/', views.change_password, name='change_password'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'),
         name='password_reset_complete'),
    path('set-password/', views.set_password, name='set_password'),
]

blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, FilterPostView, SearchPostView, post_detail, \
    post_list, category_detail, search, new_post, post_list_admin, \
    edit_post, delete_post, like_post

app_name = 'blog'
urlpatterns = [
    path('blog-list/', PostListView.as_view(), name='blog_list'),
    path('blog-detail/<slug:slug>/', PostDetailView.as_view(), name='blog_detail'),
    path('category-detail/<slug:slug>', category_detail, name='category_detail'),
    path('delete-post/<int:pk>/', delete_post, name='delete_post'),
    path('edit-post/<int:pk>/', edit_post, name='edit_post'),
    path('new-post/', new_post, name='new_post'),
    path('post-list/', post_list, name='post_list'),
    path('post-list-admin/', post_list_admin, name='post_list_admin'),
    path('post-detail/<slug:slug>/', post_detail, name='post_detail'),
    path('results/', search, name='search'),
    path('blog-list/filter', FilterPostView.as_view(), name='blog_list_filter'),
    path('blog-list/search', SearchPostView.as_view(), name='blog_list_search'),
    path('like-post/<int:pk>', like_post, name='like_post'),
]

main/urls.py
from django.urls import path
from . import views

# from .views import NewsletterUserListView, NewsletterUserDetailView
# from .api_views import CreateNewsletterUserApiView


app_name = 'main'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('about/', views.about, name='about'),
    path('user/create/', views.create_user_profile, name='create_user_profile'),
    path('user/profile/', views.user_profile, name='user_profile'),
    path('delete-user/', views.delete_user, name='delete_user'),
    path('contact/', views.contact, name='contact'),
    path('newsletter/sign-up/', views.newsletter_signup, name='newsletter_sign_up'),
    path('newsletter/unsubscribe/', views.newsletter_unsubscribe, name='newsletter_unsubscribe'),
    path('newsletter/users/', views.newsletter_users, name='newsletter_users'),
    path('newsletter/users-delete/<str:pk>/', views.newsletter_user_delete, name='newsletter_users_delete'),
    path('change-language/', views.change_language, name='change_language'),
    path('policy/', views.policy, name='policy'),
    path('accept-cookie-policy/', views.accept_cookie_policy, name='accept_cookie_policy'),
    path('cookie-banner/', views.cookie_banner, name='cookie_banner'),
    path('location/', views.api_location, name='api_location'),
    path('translate/', views.translate_app, name='translate_app'),
    path('accounts/social/signup/', views.signup_redirect, name='signup_redirect'),
    # path('newsletter/users/create/', CreateNewsletterUserApiView.as_view(), name='create_newsletter_user'),
    # path('newsletter/users/', NewsletterUserListView.as_view, name='newsletter_users'),
    # path('newsletter/users/<int:id>/', NewsletterUserDetailView.as_view, name='newsletter_user_detail'),
    path('api-avatars/', views.api_avatars, name='api_avatars'),
    path('show-avatars/', views.show_avatars, name='show_avatars'),
    path('toggle-mode/', views.toggle_mode, name='toggle_mode'),
]

plants_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

from .views import push_notification, send_push

urlpatterns = i18n_patterns(
    path('', include('main.urls')),
    path(_('admin/'), admin.site.urls),
    path('push_notification', push_notification, name='push_notification'),
    path('send_push', send_push),
    path('webpush/', include('webpush.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('authentication/', include('authentication.urls')),
    path('blog/', include('blog.urls')),
    path('control/', include('control_panel.urls')),
    path('galleries/', include('galleries.urls')),

    prefix_default_language=False,
)
# ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

if not settings.DEBUG:
    # handler = "app_name.views.function in views.py"
    handler403 = "plants_app.views.forbidden_403"
    handler404 = "plants_app.views.page_not_found_404"
    handler500 = "plants_app.views.error_500"

main/views.py
import datetime
import requests

from django import template
from django.conf import settings
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.core.mail import BadHeaderError, EmailMultiAlternatives
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import get_template
from django.utils import translation
from googletrans import Translator

from plants_app.config import pagination
from django.shortcuts import render, redirect
from django.views.generic.list import ListView

from authentication.forms import EditRegisterForm
from plants_app import settings
from .common import generate_numbers, Carousel
from .forms import UserProfileForm, ContactForm, NewsletterUserSignUpForm, UserDeleteForm
from .models import UserProfile, NewsletterUser


# class NewsletterUserListView(ListView):
#     model = NewsletterUser
#     paginate_by = 10
#
#
# class NewsletterUserDetailView(ListView):
#     model = NewsletterUser


def cookie_policy_accepted(request):
    if request.COOKIES.get('cookie_accepted', None):
        return True
    return False


def cookie_policy(request):
    return {'cookie_accepted': cookie_policy_accepted(request)}


def set_cookie(response, key, value, days_expire=7):
    if days_expire is None:
        max_age = 365 * 24 * 60 * 60  # one year
    else:
        max_age = days_expire * 24 * 60 * 60
    expires = datetime.datetime.strftime(
        datetime.datetime.utcnow() + datetime.timedelta(seconds=max_age), "%a, %d-%b-%Y %H:%M:%S GMT+1")
    response.set_cookie(key, value, max_age=max_age, expires=expires)


def accept_cookie_policy(request):
    if 'HTTP_REFERER' in request.META:
        response = HttpResponseRedirect(request.META['HTTP_REFERER'])
    else:
        response = HttpResponseRedirect('/')
    set_cookie(response, 'cookie_accepted', 1, days_expire=365)

    return response


def policy(request):
    return render(request, 'main/cookie_policy.html')


def cookie_banner(request):
    return render(request, 'main/cookie_banner.html')


def toggle_mode(request):
    if request.session.get('mode') == 'light':
        request.session['mode'] = 'dark'
        messages.info(request, 'Dark mode has been set.')
    else:
        request.session['mode'] = 'light'
        messages.info(request, 'Light mode has been set.')

    return redirect(request.GET.get('next', '/'))


def home_page(request):
    # if 'mode' not in request.session:  # Default to light mode if no mode is set
    #     request.session['mode'] = 'light'
    mode = request.session.get('mode', 'light')  # Default to light mode if no mode is set
    request.session['mode'] = mode
    request.session.modified = True

    images = Carousel.objects.all()
    weather = {}
    current_site = get_current_site(request)
    if request.method == 'POST':
        city = request.POST['city']  # Use your own api_key place api_key in place of appid ="your_api_key_here".
        lang = 'en'
        url = f'https://api.openweathermap.org/data/2.5/weather?q={city}' \
              f'&units=metric&appid=84459d8299db831d56abee888bea5970&lang={lang}'
        current_datetime = datetime.datetime.now().strftime("%B %d,  %I:%M %p")
        city_weather = requests.get(url).json()

        if city_weather['cod'] == "404" or city == "":
            messages.info(request, 'Incorrect city name, try again.')
        else:
            weather = {
                'city': city_weather['name'],
                'country_code': city_weather['sys']['country'],
                'temperature': round(city_weather['main']['temp']),
                'description': city_weather['weather'][0]['description'],
                'feels_like': round(city_weather['main']['feels_like']),
                'icon': city_weather['weather'][0]['icon'],
                'datetime': current_datetime,
            }
    else:
        weather = {}

    return render(request, 'main/home_page.html', {'weather': weather, 'current_site': current_site, 'images': images, 'mode': mode})


def api_location(request):
    # geolocation = requests.get(
    #     "https://ipgeolocation.abstractapi.com/v1/?api_key=cf3d1c1feafd4da1ae1cdcbd33082d30&"
    #     "fields=ip_address,city").json()
    images = Carousel.objects.all()
    geolocation = requests.get(
        "https://api.ipgeolocation.io/ipgeo?apiKey=a7c32a635e30443e80765774d7381a6b&fields=ip,city").json()
    geo = {
        'city': geolocation['city'],
        # 'ip_address': geolocation['ip_address'],
    }
    city = geo['city']
    url = f'https://api.openweathermap.org/data/2.5/weather?q={city}&units=metric&appid=84459d8299db831d56abee888bea5970'
    city_weather = requests.get(url).json()

    weather = {
        'city': city_weather['name'],
        'country_code': city_weather['sys']['country'],
        'temperature': round(city_weather['main']['temp']),
        'description': city_weather['weather'][0]['description'],
        'feels_like': round(city_weather['main']['feels_like']),
        'icon': city_weather['weather'][0]['icon'],
    }

    return render(request, 'main/location.html', {'weather': weather, 'images': images})


def translate_app(request):
    if request.method == "POST":
        lang = request.POST.get("lang", None)
        txt = request.POST.get("txt", None)
        translator = Translator()
        tr = translator.translate(text=txt, dest=lang)
        return render(request, 'main/translate.html', {"result": tr.text, "text": txt})
    return render(request, 'main/translate.html')


def about(request):
    return render(request, 'main/about.html')


@login_required(login_url='/authentication/login/')
def create_user_profile(request):
    instance, created = UserProfile.objects.get_or_create(user=request.user)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance)
        if form.is_valid():
            form.save()
            messages.success(request, "Your profile has been created successfully!")
            return redirect(to='create_user_profile')
    #     else:
    #         form = UserProfileForm(instance=request.user.userprofile)
    # else:
    #     form = UserProfileForm()

    return redirect('main:user_profile')
    # return render(request, 'main/create_user_profile.html', {'form': form})


@login_required(login_url='/authentication/login/')
def user_profile(request):
    if request.method == 'POST':
        register_form = EditRegisterForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=request.user.userprofile)

        if register_form.is_valid():
            register_form.save()
            messages.success(request, 'Your account information has been successfully updated!')

        elif profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile has been successfully updated!')

        else:
            messages.error(request, 'Something went wrong. You may have entered incorrect data.')
            if ValidationError:
                for error in list(profile_form.errors.values()):
                    messages.info(request, error)
                # messages.info(request, profile_form.errors)
        return redirect('main:user_profile')

    else:
        register_form = EditRegisterForm(instance=request.user)
        profile_form = UserProfileForm(instance=request.user.userprofile)

    return render(request, 'main/user_profile.html', {'user': request.user, 'register_form': register_form,
                                                      'profile_form': profile_form})


@login_required
def delete_user(request):
    if request.method == 'POST':
        # delete_form = UserDeleteForm(request.POST, instance=request.user)
        user = request.user
        user.delete()
        messages.info(request, 'Your account has been deleted.')
        return redirect('main:home_page')
    else:
        delete_form = UserDeleteForm(instance=request.user)

    return render(request, 'main/delete_user.html', {'delete_form': delete_form})


def contact(request):
    current_site = get_current_site(request)
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = f'New request: {form.cleaned_data["subject"]}'
            plaintext = template.loader.get_template('main/contact_form.txt')
            htmltemp = template.loader.get_template('main/contact_form.html')
            from_email = form.cleaned_data['email']
            body = {
                'message': form.cleaned_data['message'],
                'name': form.cleaned_data['name'],
                'domain': current_site.domain,
                'email': from_email
            }
            to_email = settings.EMAIL_HOST_USER
            send_to_me = form.cleaned_data['send_to_me']
            text_content = plaintext.render(body)
            html_content = htmltemp.render(body)
            try:
                if send_to_me:
                    msg = EmailMultiAlternatives(subject, text_content, from_email, [to_email, from_email],
                                                 headers={'Reply-To': "email@gmail.com"})
                    msg.attach_alternative(html_content, 'text/html')
                    msg.send()
                else:
                    msg = EmailMultiAlternatives(subject, text_content, from_email, [to_email],
                                                 headers={'Reply-To': "email@gmail.com"})
                    msg.attach_alternative(html_content, 'text/html')
                    msg.send()
            except BadHeaderError:
                return HttpResponse('Invalid header found.')

main/templates/main/cookie_banner.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <div id="confirmCookie">
        <p>
            We use cookies to improve user experience and our service for you.
            By clicking “Accept“, you agree to our website's cookie use as described in our Cookie Policy.
            If you do not agree to collection data by cookies, click the 'Decline all' button.
            For more information on cookies, visit the tab by clicking "More info".
            <br/>
            <a class="btn btn-primary pull-right" href="{% url 'main:accept_cookie_policy' %}">{% trans "COOKIE_INFO_OK" %}</a>
            <br/>
        </p>
    </div>
{% endblock %}

main/templates/main/create_user_profile.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}Profile{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary pull-right">Save</button>
        </form>
    {% else %}
        You must be <a href="{% url 'authentication:login_user' %}">logged in!</a>
    {% endif %}
{% endblock %}

main/templates/main/user_profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% load i18n %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load socialaccount %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                {{ message|striptags|safe|linebreaksbr|capfirst }}
            </div>
        {% endfor %}
    {% endif %}

    <!--User Bio- profile form-->
    <br>
	<div class="container mx-auto" style="text-align: center">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-4 pb-4 special-card">
                <div class="card bold-card p-4">
                    <h4 class="card-title font-weight-bold text-center">{% trans 'Profile information' %}
{#                        <img src="{% static "main/img/christmas_tree_icon.png" %}" alt="logo" width="10%">#}
                    </h4>
			      	<hr>
                    <div class="card-text">
                        {% if user.userprofile.profile_image %}
                            {% if 'avatar' in user.userprofile.profile_image.url %}
                                <img src="{{ user.userprofile.profile_image.url }}" class="rounded-circle" width="100" height="100" alt="profile_img">
                            {% else %}
                                {% thumbnail user.userprofile.profile_image "x320" as im %}
                                    <p style="text-align:center"><a href="{{ user.userprofile.profile_image.url }}">
                                        <img class="rounded-circle" width="100" height="100" src="{{ im.url }}" alt="profile_img"/></a>
                                    </p>
                                {% endthumbnail %}
                            {% endif %}
                        {% else %}
                            <img src="{% static 'main/img/default_user.jpg' %}" class="rounded-circle"
                                 style="object-fit: cover" width="100" height="100" alt="profile_img">
                        {% endif %}
                        <p class="text-muted mb-0" style="font-size: 12px">Name:</p>
                            <p>{{ user.userprofile.name }}</p>
				  		<p class="text-muted mb-0" style="font-size: 12px">Bio:</p>
                            <p>{{ user.userprofile.bio }} </p>
                        <p class="text-muted mb-0" style="font-size: 12px">Location:</p>
				  		    <p>{{ user.userprofile.location }} </p>
                        <p class="text-muted mb-0" style="font-size: 12px">Your birthdate:</p>
                            <p>{{ user.userprofile.birth_date }}</p>
                         <p class="text-muted mb-0" style="font-size: 12px">Joined:</p>
                            <p>{{ user.userprofile.join_date }}</p>
                        <p class="text-muted mb-0" style="font-size: 12px">Last login:</p>
                            <p>{{ user.last_login }}</p>
{#                        {{ user.socialaccount_set.all.0.last_login }}#}
                    </div>
                    <button type="button" class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#profileModal-profile">{% trans 'Edit profile' %}</button>
                </div>
            </div>

    <!--User- register form-->
    <div class="col-sm-12 col-md-12 col-lg-4 pb-4 special-card">
        <div class="card bold-card p-4">
            <h4 class="card-title font-weight-bold text-center">{% trans 'Hello' %}, {{ user.username }}!</h4>
            <hr>
            <div class="card-text">
                <p class="text-muted mb-0" style="font-size: 12px">Username:</p>
                <p>{{ user.username }}</p>
                {% if user.first_name %}
                    <p class="text-muted mb-0" style="font-size: 12px">Name:</p>
                    <p>{{ user.first_name }} {{ user.last_name }}</p>
                {% endif %}
                <p class="text-muted mb-0" style="font-size: 12px">Email:</p>
                <p>{{ user.email }} </p>
            </div>
            <button type="button" class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#profileModal-register">{% trans 'Edit Your information' %}</button>
        </div>

    <!-- User Account -->
    <br>
        <!-- Manage emails -->
        <div class="card bold-card p-4">
            <h4 class="card-title font-weight-bold text-center">{% trans 'Manage user account emails' %}</h4>
            <hr>
            <button type="button" class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#profileModal-emails">{% trans 'Manage account' %}</button>
        </div><br>

        <!-- Generate avatar -->
        <div class="card bold-card p-4">
            <h4 class="card-title font-weight-bold text-center">{% trans 'Generate random avatar' %}</h4>
            <hr>
            <button type="button" class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#profileModal-avatars">{% trans 'Generate avatar' %}</button>
        </div><br>
    </div>

    <!-- User Account -->
    <div class="col-sm-12 col-md-12 col-lg-4 pb-4 special-card">

        <!-- Video Area -->
        <div class="card bold-card p-4">
            <h4 class="card-title font-weight-bold text-center">{% trans 'Chillin Music Set' %}
{#                <img src="{% static "main/img/christmas_icon1.png" %}" alt="logo" width="10%">#}
            </h4>
            <hr>
            <div class="video-area mb-100">
                <iframe width="350" height="270" allowfullscreen="true" src="https://www.youtube.com/embed/pYDfz8-geZ4"></iframe>
            </div>
        </div>
        <br>

        <!-- Delete account -->
        <div class="card bold-card p-4">
            <h4 class="card-title font-weight-bold text-center">{% trans 'Delete user account' %}</h4>
            <hr>
            <button type="button" class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#profileModal-account">{% trans 'Delete account' %}</button>
        </div>
    </div>

    <!--Edit User-->
    <div class="col-sm-12 col-md-12 col-lg-9 pb-4">
        <div class="modal fade" tabindex="-1" id="profileModal-register" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title text-center">{% trans 'Edit Information' %}:</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                    </div>
                    <div class="modal-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ register_form|crispy }}
                            <div class="modal-footer">
                                {% if user.socialaccount_set.exists %}
                                    <a class="btn btn-info" href="{% url 'authentication:set_password' %}" role="button">Set password</a>
                                {% else %}
                                    <a class="btn btn-info" href="{% url 'authentication:change_password' %}" role="button">Change password</a>
                                {% endif %}
                                <button type="submit" class="btn btn-primary">Save changes</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Edit User Bio-->
    <div class="col-sm-12 col-md-12 col-lg-9 pb-4">
        <div class="modal fade" tabindex="-1" id="profileModal-profile" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">{% trans 'Edit Profile' %}:</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                    </div>
                    <div class="modal-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ profile_form|crispy }}
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary">Save changes</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Manage User Account Emails-->
    <div class="col-sm-10 col-md-10 col-lg-8 pb-4">
        <div class="modal fade" tabindex="-1" id="profileModal-emails" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title text-center">{% trans 'Manage Account' %}:</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p style="text-align: center">
                            {% trans 'Here you can manage your social accounts email.' %}<br>
                            {% trans 'To log in your account using the google option, you must first link google email/emails to this profile.' %}
                        </p><hr>
                        <div class="form-group">
                            <a href="/accounts/email"><button class="btn btn-primary">Manage</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </div>

    <!--Delete User Account-->
    <div class="col-sm-10 col-md-10 col-lg-8 pb-4">
        <div class="modal fade" tabindex="-1" id="profileModal-account" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title text-center">{% trans 'Delete Account' %}:</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                    </div>
                    <div class="modal-body">
                        <p style="text-align: center">
                            {% trans 'Are you sure you want to delete your account?' %}
                            {% trans 'If you delete account your profile will be deleted as well as all your blog posts.' %}
                        </p><hr>
                        <div class="form-group">
                            <a href="{% url 'main:delete_user' %}"><button class="btn btn-danger">Delete <i class="fa fa-trash"></i></button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </div>

    <!--Generate Random Avatar-->
    <div class="col-sm-10 col-md-10 col-lg-8 pb-4">
        <div class="modal fade" tabindex="-1" id="profileModal-avatars" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title text-center">{% trans 'Generate Avatar' %}:</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                    </div>
                    <div class="modal-body">
                        <p style="text-align: center">
                            {% trans 'Here you can generate random avatars for your profile image.' %}
                            {% trans 'Choose button with your gender to generate and save random avatar.' %}
                            {% trans 'You can generate multiple avatars if you want.' %}
                        </p><hr>
                        <div class="form-group">
                            <a href="{% url 'main:show_avatars' %}"><button class="btn btn-info">Show avatars</button></a>
                            <a href="{% url 'main:api_avatars' %}?gender=female"><button class="btn btn-primary">Generate Female</button></a>
                            <a href="{% url 'main:api_avatars' %}?gender=male"><button class="btn btn-primary">Generate Male</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </div>
{% endblock %}