blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, FilterPostView, SearchPostView, post_detail, \
    post_list, category_detail, search, new_post, post_list_admin, \
    edit_post, delete_post, like_post

app_name = 'blog'
urlpatterns = [
    path('blog-list/', PostListView.as_view(), name='blog_list'),
    path('blog-detail/<slug:slug>/', PostDetailView.as_view(), name='blog_detail'),
    path('category-detail/<slug:slug>', category_detail, name='category_detail'),
    path('delete-post/<int:pk>/', delete_post, name='delete_post'),
    path('edit-post/<int:pk>/', edit_post, name='edit_post'),
    path('new-post/', new_post, name='new_post'),
    path('post-list/', post_list, name='post_list'),
    path('post-list-admin/', post_list_admin, name='post_list_admin'),
    path('post-detail/<slug:slug>/', post_detail, name='post_detail'),
    path('results/', search, name='search'),
    path('blog-list/filter', FilterPostView.as_view(), name='blog_list_filter'),
    path('blog-list/search', SearchPostView.as_view(), name='blog_list_search'),
    path('like-post/<int:pk>', like_post, name='like_post'),
]

control_panel/urls.py
from django.urls import path

from . import views


app_name = 'control_panel'
urlpatterns = [
    path('newsletter/', views.control_newsletter, name='control_newsletter'),
    path('newsletter-list/', views.control_newsletter_list, name='control_newsletter_list'),
    path('newsletter-detail/<int:pk>', views.control_newsletter_edit, name='control_newsletter_edit'),
    path('newsletter-edit/<int:pk>', views.control_newsletter_edit, name='control_newsletter_edit'),
    path('newsletter-delete/<int:pk>', views.control_newsletter_delete, name='control_newsletter_delete'),
    path('carousel/', views.control_carousel, name='control_carousel'),
    path('carousel-list/', views.control_carousel_list, name='control_carousel_list'),
    path('carousel-delete/<int:pk>', views.control_carousel_delete, name='control_carousel_delete'),
]

main/urls.py
from django.urls import path
from . import views

# from .views import NewsletterUserListView, NewsletterUserDetailView
# from .api_views import CreateNewsletterUserApiView


app_name = 'main'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('about/', views.about, name='about'),
    path('user/create/', views.create_user_profile, name='create_user_profile'),
    path('user/profile/', views.user_profile, name='user_profile'),
    path('delete-user/', views.delete_user, name='delete_user'),
    path('contact/', views.contact, name='contact'),
    path('newsletter/sign-up/', views.newsletter_signup, name='newsletter_sign_up'),
    path('newsletter/unsubscribe/', views.newsletter_unsubscribe, name='newsletter_unsubscribe'),
    path('newsletter/users/', views.newsletter_users, name='newsletter_users'),
    path('newsletter/users-delete/<str:pk>/', views.newsletter_user_delete, name='newsletter_users_delete'),
    path('change-language/', views.change_language, name='change_language'),
    path('policy/', views.policy, name='policy'),
    path('accept-cookie-policy/', views.accept_cookie_policy, name='accept_cookie_policy'),
    path('cookie-banner/', views.cookie_banner, name='cookie_banner'),
    path('location/', views.api_location, name='api_location'),
    path('translate/', views.translate_app, name='translate_app'),
    path('accounts/social/signup/', views.signup_redirect, name='signup_redirect'),
    # path('newsletter/users/create/', CreateNewsletterUserApiView.as_view(), name='create_newsletter_user'),
    # path('newsletter/users/', NewsletterUserListView.as_view, name='newsletter_users'),
    # path('newsletter/users/<int:id>/', NewsletterUserDetailView.as_view, name='newsletter_user_detail'),
    path('api-avatars/', views.api_avatars, name='api_avatars'),
    path('show-avatars/', views.show_avatars, name='show_avatars'),
    path('toggle-mode/', views.toggle_mode, name='toggle_mode'),
]

plants_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

from .views import push_notification, send_push

urlpatterns = i18n_patterns(
    path('', include('main.urls')),
    path(_('admin/'), admin.site.urls),
    path('push_notification', push_notification, name='push_notification'),
    path('send_push', send_push),
    path('webpush/', include('webpush.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('authentication/', include('authentication.urls')),
    path('blog/', include('blog.urls')),
    path('control/', include('control_panel.urls')),
    path('galleries/', include('galleries.urls')),

    prefix_default_language=False,
)
# ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

if not settings.DEBUG:
    # handler = "app_name.views.function in views.py"
    handler403 = "plants_app.views.forbidden_403"
    handler404 = "plants_app.views.page_not_found_404"
    handler500 = "plants_app.views.error_500"

control_panel/forms.py
from django import forms

from main.models import Newsletter
from main.common import Carousel


class NewsletterCreationForm(forms.ModelForm):

    class Meta:
        model = Newsletter
        fields = ['subject', 'body', 'status']


class CarouselCreationForm(forms.ModelForm):

    class Meta:
        model = Carousel
        fields = '__all__'

control_panel/views.py
from django import template
from django.conf import settings
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.core.mail import send_mail, EmailMultiAlternatives, BadHeaderError
from django.http import HttpResponse
from django.template.loader import get_template
from django.shortcuts import render, get_object_or_404, redirect

from control_panel.forms import NewsletterCreationForm, CarouselCreationForm
from main.common import Carousel
from plants_app.config import pagination
from main.models import Newsletter, NewsletterUser

# # @login_required(login_url='/authentication/login/')
# @staff_member_required
# def control_newsletter(request):
#     form = NewsletterCreationForm(request.POST or None)
#     if form.is_valid():
#         instance = form.save()
#         messages.success(request, 'Newsletter has been successfully created.')
#         newsletter = Newsletter.objects.get(id=instance.id)
#         if newsletter.status == "Published":
#             subject = f"Newsletter from Watering Plant App: {newsletter.subject}"
#             body = newsletter.body
#             from_email = settings.EMAIL_HOST_USER
#             for email in newsletter.email.all():
#                 send_mail(subject=subject, message=body, from_email=from_email,
#                           recipient_list=[email], fail_silently=True)
#
#     form = NewsletterCreationForm()
#     context = {'form': form}
#     template = 'control_panel/control_newsletter.html'
#     return render(request, template, context)
from plants_app.settings import env


@staff_member_required(login_url='/authentication/login/')
def control_newsletter(request):
    form = NewsletterCreationForm(request.POST or None)
    if form.is_valid():
        instance = form.save()
        messages.success(request, 'Newsletter has been successfully created.')
        newsletter = Newsletter.objects.get(id=instance.id)

        if newsletter.status == "Published":
            subject = f"New newsletter from Watering Plant App: {newsletter.subject}"
            body = {'body': newsletter.body}
            plaintext = template.loader.get_template('control_panel/newsletter_form.txt')
            htmltemp = template.loader.get_template('control_panel/newsletter_form.html')
            from_email = settings.EMAIL_HOST_USER
            text_content = plaintext.render(body)
            html_content = htmltemp.render(body)
            emails = NewsletterUser.objects.all().values_list('email', flat=True)
            for email in emails:
                try:
                    msg = EmailMultiAlternatives(subject, text_content, from_email, [email],
                                                 headers={'Reply-To': from_email})
                    msg.attach_alternative(html_content, 'text/html')
                    msg.send()
                except BadHeaderError:
                    return HttpResponse('Invalid header found.')

            messages.success(request, 'New newsletter was sent successfully.')
            return redirect('control_panel:control_newsletter_list')
        return redirect('control_panel:control_newsletter_list')
    else:
        form = NewsletterCreationForm()

    return render(request, 'control_panel/control_newsletter.html', {'form': form})


@staff_member_required(login_url='/authentication/login/')
def control_newsletter_list(request):
    newsletters = Newsletter.objects.all()
    pages = pagination(request, newsletters, 15)

    template = 'control_panel/control_newsletter_list.html'
    context = {
        'control_newsletter_list': pages,
        'page_obj': pages
    }

    return render(request, template, context)


# def control_newsletter_detail(request, pk):
#     newsletter = get_object_or_404(Newsletter, pk=pk)
#
#     context = {
#         'newsletter': newsletter
#     }
#     template = 'control_panel/control_newsletter_detail.html'
#     return render(request, template, context)


@staff_member_required(login_url='/authentication/login/')
def control_newsletter_edit(request, pk):
    newsletter = get_object_or_404(Newsletter, pk=pk)
    if request.method == 'POST':
        form = NewsletterCreationForm(request.POST, instance=newsletter)
        if form.is_valid():
            newsletter = form.save()
            if newsletter.status == 'Published':
                subject = f"New newsletter from Watering Plant App: {newsletter.subject}"
                body = {'body': newsletter.body}
                plaintext = template.loader.get_template('control_panel/newsletter_form.txt')
                htmltemp = template.loader.get_template('control_panel/newsletter_form.html')
                from_email = settings.EMAIL_HOST_USER
                text_content = plaintext.render(body)
                html_content = htmltemp.render(body)
                emails = NewsletterUser.objects.all().values_list('email', flat=True)
                for email in emails:
                    try:
                        msg = EmailMultiAlternatives(subject, text_content, from_email, [email],
                                                     headers={'Reply-To': from_email})
                        msg.attach_alternative(html_content, 'text/html')
                        msg.send()
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')

            messages.success(request, "Newsletter has been edited successfully!")
            return redirect('control_panel:control_newsletter_list')
    else:
        form = NewsletterCreationForm(instance=newsletter)

    return render(request, 'control_panel/control_newsletter.html', {'form': form})


@staff_member_required(login_url='/authentication/login/')
def control_newsletter_delete(request, pk):
    newsletter = get_object_or_404(Newsletter, pk=pk)
    if request.method == 'POST':
        newsletter.delete()
        messages.success(request, 'Newsletter has been deleted.')
        return redirect('control_panel:control_newsletter_list')

    return render(request, 'control_panel/control_newsletter_delete.html', {'newsletter': newsletter})


@staff_member_required(login_url='/authentication/login/')
def control_carousel(request):
    if request.method == "POST":
        form = CarouselCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your carousel has been created successfully.')
            return redirect('control_panel:control_carousel')
        else:
            messages.error(request, f'Something went wrong!\n\n {form.errors}')
            return redirect('control_panel:control_carousel')
    else:
        form = CarouselCreationForm()
    return render(request, "control_panel/control_carousel.html", {"form": form})


@staff_member_required(login_url='/authentication/login/')
def control_carousel_list(request):
    carousel = Carousel.objects.all()
    pages = pagination(request, carousel, 10)

    template = 'control_panel/control_carousel_list.html'
    context = {
        'control_carousel_list': pages,
        'page_obj': pages
    }

    return render(request, template, context)


@staff_member_required(login_url='/authentication/login/')
def control_carousel_delete(request, pk):
    carousel = get_object_or_404(Carousel, pk=pk)
    if request.method == 'POST':
        carousel.delete()
        messages.success(request, 'Carousel photo has been deleted.')
        return redirect('control_panel:control_carousel_list')

    return render(request, 'control_panel/control_carousel_delete.html', {'carousel': carousel})

control_panel/templates/control_panel/control_carousel.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                {{ message|striptags|safe|linebreaksbr }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="flower-background p-4">
        <div class="col-sm-8 col-md-8 col-lg-12 pb-4">
            <div class="container">
                <div class="row justify-content-center">
                    <h2 class="page-header" style="color: darkslateblue"><b>Carousel</b></h2><hr>
                    <h5 style="text-align: center; color: darkslateblue"><b>Add new photo to home page carousel:</b></h5>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy|linebreaks }}
                        {{ form.media }}<br>
                        <div style="text-align: right">
                            <button class="btn btn-primary" type="submit">Save</button>
                            <a class="btn btn-secondary" href="{% url 'main:home_page' %}" role="button">Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

control_panel/templates/control_panel/control_carousel_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row justify-content-center">
	<div class="col-md-6">
		<div class="card card-body">
			<p style="text-align: center">Are you sure you want to delete: "{{ carousel }}"?</p>
			<form action="{% url 'control_panel:control_carousel_delete' carousel.id  %}" method="POST">
				{% csrf_token %}
                <p style="text-align: center">
                    <input class="btn btn-primary" type="submit" value="Confirm">
                    <a class="btn btn-danger" href="{% url 'control_panel:control_carousel_list' %}">Cancel</a>
                </p>
			</form>
		</div>
	</div>
</div>
{% endblock %}

control_panel/templates/control_panel/control_carousel_list.html
{% extends 'base.html' %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                {{ message|striptags|safe|linebreaksbr }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="row">
            <div style="text-align: inherit; font-size: medium">
                <h5 class="page-header"><b>All Carousel's photos</b></h5><br>
            </div>
        </div>
    </div>

    <div class="card card-body special-cards">
{#    <div class="table-responsive table-hover">#}
        <table class="table">
            <thead class="thead-dark">
                <tr style="text-align: center">
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Created</th>
                    <th scope="col">Updated</th>
{#                    <th scope="col">Edit</th>#}
{#                    <th scope="col">Delete</th>#}
                </tr>
            </thead>
            <tbody>
            {% for item in control_carousel_list %}
                <tr style="text-align: center">
                    <td>{{ item.title }}</td>
                    <td>{{ item.sub_title }}</td>
                    <td>{{ item.created }}</td>
                    <td>{{ item.updated }}</td>
                    <td><a href="{% url 'control_panel:control_carousel_delete' pk=item.pk %}"><button class="btn btn-danger">Delete</button></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div><br>
    {% include 'pagination.html' %}
    <footer>
        <div style="text-align: right; font-size: medium">
            <button type="button" class="btn btn-light btn-sm">
                <a href="{% url 'main:home_page' %}" class="nav-link">Back</a>
            </button>
        </div>
    </footer>
    <br><br>
{% endblock %}

control_panel/templates/control_panel/control_newsletter.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h1 class="page-header">Newsletter</h1>
        {% if messages %}
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                    {{ message|striptags|safe|linebreaksbr }}
                </div>
            {% endfor %}
        {% endif %}
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            {{ form.media }}
            <br>
            <div style="text-align: right">
                <button class="btn btn-primary" type="submit">Save</button>
                <a class="btn btn-dark" href="{% url 'control_panel:control_newsletter_list' %}" role="button">Back</a>
            </div>
        </form>
    </div><br>
{% endblock %}

control_panel/templates/control_panel/control_newsletter_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row justify-content-center">
	<div class="col-md-6">
		<div class="card card-body">
			<p style="text-align: center">Are you sure you want to delete: "{{ newsletter }}"?</p>
			<form action="{% url 'control_panel:control_newsletter_delete' newsletter.id  %}" method="POST">
				{% csrf_token %}
                <p style="text-align: center">
                    <input class="btn btn-primary" type="submit" value="Confirm">
                    <a class="btn btn-danger" href="{% url 'control_panel:control_newsletter_list' %}">Cancel</a>
                </p>
			</form>
		</div>
	</div>
</div>
{% endblock %}

control_panel/templates/control_panel/control_newsletter_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="page-header">
            <h3>{{ newsletter.subject }}</h3>
        </div>
    <br>
    <div style="text-align: center; font-size: medium">
        <label>
            <textarea rows="5" cols="25">{{ newsletter.body }}</textarea>
        </label>
    </div>
    </div>
    <br>
        <div style="text-align: inherit; font-size: small">
            <button type="button" class="btn btn-light">
                <a href="{% url 'control_panel:control_newsletter' %}" class="btn">New</a>
            </button>
            <button type="button" class="btn btn-light">
                <a href="{% url 'control_panel:control_newsletter_edit' pk=newsletter.pk %}" class="btn">Edit</a>
            </button>
            <button type="button" class="btn btn-light">
                <a href="{% url 'control_panel:control_newsletter_delete' pk=newsletter.pk %}" class="btn">Delete</a>
            </button>
        </div>
    <br><br><br>
    <footer>
        <div style="text-align: right; font-size: medium">
            <button type="button" class="btn btn-light">
                <a href="{% url 'control_panel:control_newsletter_list' %}" class="nav-link">Back</a>
            </button>
        </div>
    </footer>
{% endblock %}

control_panel/templates/control_panel/control_newsletter_list.html
{% extends 'base.html' %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                {{ message|striptags|safe|linebreaksbr }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="row">
            <div style="text-align: inherit; font-size: medium">
                <h5 class="page-header"><b>All Newsletters</b></h5><br>
            </div>
        </div>
    </div>
    <div class="card card-body special-cards">
{#    <div class="table-responsive table-hover">#}
        <table class="table">
            <thead class="thead-dark">
                <tr style="text-align: center">
                    <th scope="col">Subject</th>
                    <th scope="col">Status</th>
                    <th scope="col">Created</th>
                    <th scope="col">Updated</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
            {% for item in control_newsletter_list %}
                <tr style="text-align: center">
                    <td>{{ item.subject }}</td>
                    <td>{{ item.status }}</td>
                    <td>{{ item.created }}</td>
                    <td>{{ item.updated }}</td>
                    <td><a href="{% url 'control_panel:control_newsletter_edit' pk=item.pk %}"><button class="btn btn-warning">Edit</button></a></td>
                    <td><a href="{% url 'control_panel:control_newsletter_delete' pk=item.pk %}"><button class="btn btn-danger">Delete</button></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div><br/>
    {% include 'pagination.html' %}
    <footer>
    <br>
        <div style="text-align: right; font-size: medium">
            <button type="button" class="btn btn-light btn-sm">
                <a href="{% url 'control_panel:control_newsletter' %}" class="nav-link">New newsletter</a>
            </button>
            <button type="button" class="btn btn-light btn-sm">
                <a href="{% url 'main:home_page' %}" class="nav-link">Back</a>
            </button>
        </div>
    </footer>
    <br><br>
{% endblock %}

control_panel/templates/control_panel/control_send_reminder.html
{% extends 'base.html' %}

{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
            {{ message|striptags|safe|linebreaksbr }}
        </div>
    {% endfor %}
{% endif %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="row">
            <div style="text-align: inherit; font-size: medium">
                <h5 class="page-header"><b>All users reminder:</b></h5><br>
            </div>
        </div>
    </div>
    <div class="card card-body special-cards">
{#    <div class="table-responsive table-hover">#}
        <table class="table">
            <thead class="thead-dark">
                <tr style="text-align: center">
                    <th scope="col">Gallery Author</th>
                    <th scope="col">Gallery Title</th>
                    <th scope="col">Photo Title</th>
                    <th scope="col">How Often</th>
                    <th scope="col">Created/Updated</th>

                </tr>
            </thead>
            <tbody>
            {% for photo in all_photos %}
                <tr style="text-align: center">
                    <td>{{ photo.gallery.author }}</td>
                    <td>{{ photo.gallery.title }}</td>
                    <td>{{ photo.title}}</td>
                    <td>{{ photo.how_often }}</td>
                    {% if photo.created != photo.updated %}
                        <td>U: {{ photo.updated }}</td>
                    {% else %}
                        <td>C: {{ photo.created }}</td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <footer>
    <br>
        <div style="text-align: right; font-size: medium">
            <button type="button" class="btn btn-light btn-sm">
                <a href="{% url 'main:home_page' %}" class="nav-link">Back</a>
            </button>
        </div>
    </footer>
    <br/><br/>
{% endblock %}

control_panel/templates/control_panel/newsletter_form.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="">
  <head>
    <title>HTML email template</title>
    <meta name="viewport" content="width = 375, initial-scale = -1">
  </head>
  <body style="background-color: lightgray; font-size: 16px;">
    <div style="text-align: center;">
      <table align="center" border="0" cellpadding="0" cellspacing="0" style="height:100%; width:600px;">
          <!-- BEGIN EMAIL -->
          <tr>
            <td align="center" bgcolor="#f5f5f5" style="padding:30px">
               <p style="text-align:left">
                   <b><i>Your weekly newsletter: </i></b>
                   <br>
               </p>
                <p style="text-align:left">
                    {{ body|safe }}
                </p>
                <br><br>
                <p style="text-align:left">For more visit our website:
                    <a href="{{ 'https' }}://{{ 'plants-mw.herokuapp.com/' }}"><b>watering-plants-app.com</b></a>
                </p>
                <p style="text-align:left">
                    Kind regards,<br>The Watering Plants Application Team
                </p>
            </td>
          </tr>
      </table>
    </div>
  </body>
</html>